# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84f70dc4996672670e8954fd72da22a60c8ff11f188f0c94271cf83484e10f5c4060adfdc603579fd3841c563fdb13c3e31ac22b547cb7374581508f825e2af1

test:
  secret_key_base: 891b805291c2894d99da83dcc7f8c30abcb73a18c805a62336383e966f2345f0f111e3c19a01975634e5954755f7bc3cf3c5d2633bdab1272ede476e67220599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
